### ISSUE TITLE
Docker / ptvsd / Django: Failed to attach (connect ECONNREFUSED )

### ISSUE THREAD

**Issue by Lynaj** [microsoft/ptvsd#1704]
I am trying to implement a debugging plugin ptvsd into my existing dockerized application

Running on Google Compute Engine with Ubuntu 18.04. The entire application is containerized with Docker-Compose. Back-end Plugin: Django

manage.py:

```
#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys
import ptvsd

def main():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'djangoserver.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc

    ptvsd.enable_attach(address=('0.0.0.0', 5050))
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()

```

Launch.json

```
{
            "name": "Attach Remote Django",
            "type": "python",
            "request": "attach",
            "pathMappings": [
                "localRoot": "${workspaceRoot}/djangoserver",
                "remoteRoot": "/usr/src/"
            ],
            "port": 5050,
            "secret": "secret",
            "host": "localhost"
}
```

docker-compose.yml
```
  web:
    build: ./djangoserver
    command: gunicorn djangoserver.wsgi:application --noreload --nothreading --bind 0.0.0.0:8001 
    volumes:
      - ./djangoserver:/usr/src
    # entrypoint: /entrypoint.sh
    ports:
      - 5050:5050
    expose:
      - 8001
    env_file: .env.dev
    depends_on:
      - db_development_2
    stdin_open: true
```

Whenever i a do build and run the docker-composer, it starts without any problems, but later on, when I am trying to connect to the server with the debugger, I receive following error:

```
Failed to attach (connect ECONNREFUSED 127.0.0.1:5050)
```
