### ISSUE TITLE
Attach PTVSD to multiple Docker containers 

### ISSUE THREAD

**Issue by vermaat** [microsoft/ptvsd#2131]
## Environment data

- PTVSD version: ptvsd==4.3.2
- OS and version: MacOS Mojave
- Python version (& distribution if applicable, e.g. Anaconda): python:3.6.10-slim-buster (Through Dockerfile)
- Using VS Code or Visual Studio: VS Code, May 2020 (version 1.46)

## Actual behavior

Cannot add PTVSD to a second Docker container. I'm only getting it to work with 1 container (no errors).

## Expected  behavior

A method/ fix to attach PTVSD to multiple Docker containers simultaneously 

## Steps to reproduce:

I have a Flask project that runs in a Docker container 'web' (through Docker-Compose), and I'm using PTVSD to succesfully debug code inside the 'web' container using the following code:

launch.json
```
...{
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "127.0.0.1",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "/app"
                }
            ]
        },....
   
```
docker-compose.yml 

```
web:
    ....
    environment:
      - CONTAINER_NAME=web
    ports:
      - 5678:5678
     ....
```

app.py
```
...
if app.config.get('DOCKER_CONTAINER_NAME') == 'web':
        import ptvsd
        print("Waiting for debugger attach")
        ptvsd.enable_attach(address=('0.0.0.0', 5678), redirect_output=True)
        ptvsd.wait_for_attach()
        # breakpoint()
        print('PTVSD Web Debugger attached')
```

(the above works great)

I'm using Celery for background Flask tasks. Therefore I'm running a second Docker container 'worker' that runs the same code as the 'web' container. So often my 'Web' Flask code sends a task (through Celery/Redis) to the 'worker' Flask code (running the same code base) so PTVSD cannot stop on breakpoints on the 'worker'

PTVSD is of course only connected to the 'web' container for debugging so I've been trying to add PTVSD also to the 'worker' container, without any luck.

I've tried to use a 2nd launch.json command that connects to PTVSD on a different port (5679), load PTVSD in 'app.py' with 5679, and open the port 5679 in the 'worker' container through Docker-Compose. I assigned a 'CONTAINER_NAME' env var to each Docker container so in my 'app.py' i can let the Web and Worker container run slightly different commands (like different PTVSD commands). Using the code below I can still attach to the Web container, but I'm unable to attach (using the Worker launch.json) to the worker PTVSD (it keeps saying 'Waiting to attach') and the launch.json action keeps spinning (looking for PTVSD i guess).

launch.json
```
...{
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "127.0.0.1",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "/app"
                }
            ]
        },
        {
            "name": "Python: Remote Attach Worker",
            "type": "python",
            "request": "attach",
            "port": 5679,
            "host": "127.0.0.1",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "/app"
                }
            ]
        },,....
   
```
docker-compose.yml 

```
web:
    build:
      context: "."
      args:
        - "FLASK_ENV=${FLASK_ENV:-production}"
    depends_on:
      - "postgres"
      - "redis"
    env_file:
      - ".env"
    environment:
      - CONTAINER_NAME=web
    ports:
      - "${DOCKER_WEB_PORT:-127.0.0.1:8000}:8000"
      - 5678:5678
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - "${DOCKER_WEB_VOLUME:-./public:/app/public}"
    stdin_open: true
    tty: true
    

  worker:
    build:
      context: "."
      args:
        - "FLASK_ENV=${FLASK_ENV:-production}"
    command: celery worker -l debug --pool=eventlet -c=500 --broker=redis://redis:6379/0
    depends_on:
      - "postgres"
      - "redis"
    env_file:
      - ".env"
    environment: 
      - CONTAINER_NAME=worker
    ports:
      - 5679:5679
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - "${DOCKER_WEB_VOLUME:-./public:/app/public}"
```

app.py
```
...
if app.config.get('DOCKER_CONTAINER_NAME') == 'web':
        import ptvsd
        print("Waiting for web debugger attach")
        ptvsd.enable_attach(address=('0.0.0.0', 5678), redirect_output=True)
        ptvsd.wait_for_attach()
        # breakpoint()
        print('PTVSD Web Debugger attached')

if app.config.get('DOCKER_CONTAINER_NAME') == 'worker':
        import ptvsd
        print("Waiting for worker debugger attach")
        ptvsd.enable_attach(address=('0.0.0.0', 5679), redirect_output=True)
        ptvsd.wait_for_attach()
        # breakpoint()
        print('PTVSD Worker Debugger attached')
```

I also tried attaching PTSVD in the web and worker container both under the same port in app.py and the Docker-compose file, but then Docker complains that the port is un use, which seems logical.

Any guidance would be greatly appriciated.
